# Template para Hyprland
# .default.with_alpha(0.8).hex
$main_container = rgba(004c6aee)
$tm_container = rgba(c5e7ff)
$s_container = rgba(374955)
$ts_conatiner = rgba(d2e5f4)
$bg_transparent = rgba(41484dee)
$bgt_text = rgb(c1c7ce)
$border_color = rgb(8b9297)
