# Template para Hyprland
# .default.with_alpha(0.8).hex
$main_container = rgba(374379ee)
$tm_container = rgba(dde1ff)
$s_container = rgba(424659)
$ts_conatiner = rgba(dfe1f9)
$bg_transparent = rgba(45464fee)
$bgt_text = rgb(c6c5d0)
$border_color = rgb(90909a)
