@define-color input_bgcolor {{colors.primary_container.default.rgba}};
@define-color entry_container {{colors.secondary_container.default.rgba}};
@define-color entry-text {{colors.on_secondary_container.default.rgba}};
@define-color text_input_color {{colors.on_primary_container.default.rgba}};
@define-color background rgba({{colors.surface_variant.default.red}}, {{colors.surface_variant.default.green}}, {{colors.surface_variant.default.blue}}, 0.8);
@define-color text1 {{colors.on_surface_variant.default.rgba}};
@define-color border_color {{colors.outline.default.rgba}};