# Template para Hyprland
# .default.with_alpha(0.8).hex
$main_container = rgba({{colors.primary_container.default.hex_stripped}}ee)
$tm_container = rgba({{colors.on_primary_container.default.hex_stripped}})
$s_container = rgba({{colors.secondary_container.default.hex_stripped}})
$ts_conatiner = rgba({{colors.on_secondary_container.default.hex_stripped}})
$bg_transparent = rgba({{colors.surface_variant.default.hex_stripped}}ee)
$bgt_text = rgb({{colors.on_surface_variant.default.hex_stripped}})
$border_color = rgb({{colors.outline.default.hex_stripped}})
