@define-color main_accent {{colors.primary.default.rgba}};
@define-color text2 {{colors.on_primary.default.rgba}};
@define-color background {{colors.surface_variant.default.rgba}};
@define-color text1 {{colors.on_surface_variant.default.rgba}};
@define-color border_color {{colors.outline.default.rgba}};